export const FETCH_CURRENCY_LIST = "FETCH_CURRENCY_LIST";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const LOG_IN_USER = "LOG_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";

export const GET_COINS_TYPES = "GET_COINS_TYPES";
export const GET_CERTAIN_COIN_INFO = "GET_CERTAIN_COIN_INFO";
export const DELETE_CERTAIN_COIN_INFO = "DELETE_CERTAIN_COIN_INFO"
